apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t2-provisioner-log-pvc
  namespace: cms-ucsd-t2
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
